import Lax52Proofs.Regular
import Lax52Proofs.SemanticTransport
import Lax52Proofs.ValidMarkedWordsRegular
import Lax52Proofs.MSOFormulaRegularity
import Lax52Proofs.MSOToNFA
import Lax52Proofs.NFAToMSO
import Lax52Proofs.MSOAutomataEquivalence
